repositoryID: 55d8a876-eb29-457e-bb62-2eaa09e4e99b
owners: # (optional, used to claim repository ownership)
  - name: featureform
    email: hello@featureform.com
ignore: # (optional, packages that should not be indexed by Artifact Hub)
  - name: etcd
