apiVersion: v1
entries:
  etcd:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 3.5.3
    created: "2022-05-31T17:30:24.840353-07:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: etcd is a distributed key-value store designed to securely store
      data across a cluster. etcd is widely used in production on account of its reliability,
      fault-tolerance and ease of use.
    digest: 11ea12295f14847a72a1c6f97b0bd652f3407c4e6e69b3e7d78a38742b3dae37
    home: https://github.com/bitnami/charts/tree/master/bitnami/etcd
    icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-220x234.png
    keywords:
    - etcd
    - cluster
    - database
    - cache
    - key-value
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: etcd
    sources:
    - https://github.com/bitnami/bitnami-docker-etcd
    - https://coreos.com/etcd/
    urls:
    - charts/etcd-8.0.1.tgz
    version: 8.0.1
generated: "2022-05-31T17:30:24.837782-07:00"
